server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/names?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: FORget2011
  redis:
    database: 10
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5

logging:
  level:
    run.zhinan.names: DEBUG